### ISSUE TITLE
Adding properties not working with Storybook

### ISSUE THREAD

**Issue by simonljus** [himynameisdave/svelte-flex#4]
Version: 1.1.0
I am not sure if there is a problem with Storybook, this module or my setup... 

I have a story with a custom component having a Flex component (imported from the package) and another custom component. 
It is not possible to set attributes on the Flex component (that uses $$restProps) but it is possible to set on any of my child components (that uses $$restProps).
I am also using svelte-material-UI in my project and the attributes are passed down correctly (seems to use a custom object with $$props).

I do not have any issues when using this module in my svelte-project.

**Comment by himynameisdave** [comment]
Hey @simonljus! Thanks for filing this issue. While it sounds like an issue with Storybook, I would still like to investigate it further to ensure that prop spreading works for svelte-flex. Thanks for mentioning svelte-material-ui, I'll check it out and see what they're doing.

In the meantime, do you mind posting as much additional info as possible about your setup? Even just the story which uses svelte-flex and MUI together would be great.

Thanks for using svelte-flex!

**Comment by simonljus** [comment]
I forked the sapper-template that I used and added my configurations. I added a login form component that exists on the page and in a story. 
The component on the webpage has the class and the title attribute.
The component in the story does not have it. 
https://github.com/simonljus/sapper-template-rollup

**Comment by himynameisdave** [comment]
This seems to be an issue in Storybook and not with `svelte-flex`. As far as I can tell, your example using `svelte-material-ui` is [passing down known props](https://github.com/simonljus/sapper-template-rollup/blob/master/src/components/forms/Loginform.svelte#L19-L20), that is, props which are [known and specified](https://sveltematerialui.com/demo/textfield) by that library (ie: not [`$$restProps`](https://svelte.dev/docs#Attributes_and_props)). I believe this is why your MUI stuff works in Storybook but `svelte-flex` does not.

I would recommend [filing an issue in the Storybook](https://github.com/storybookjs/storybook/issues/new?template=bug_report.md) repo, as [it seems that `$$restProps` are not passed down](https://github.com/storybookjs/storybook/blob/master/app/svelte/src/client/preview/render.ts#L53-L57) in stories (as far as I can tell).

Closing this issue here as it's out of scope for this project, but willing to reopen if new information is provided.
